CXX     = g++
CXXFLAGS = -Wall -std=c++17
TARGET   = divide_and_conquer_demo
SRC     = divide_and_conquer_demo.cpp

$(TARGET): $(SRC)
        $(CXX) $(CXXFLAGS) $(SRC) -o $(TARGET)

.PHONY: clean
clean:
        rm -f $(TARGET)